#!/usr/bin/env bash

set -e

base="${DOTFILES_HOME:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
home="$HOME"
config="${XDG_CONFIG_HOME:-"$home/.config"}"

link() {
    target="$1"
    from="$base/$target"
    to="${2:-$config/$1}"
    to_parent="$(dirname "$to")"

    if [ ! -d "$to_parent" ]; then
        mkdir -p "$to_parent"
    fi

    echo "Linking $target to $to"

    ln -fns "$from" "$to"
}

link_all() {
    target="$1"
    from="$base/$target"
    to="$2"

    if [ ! -d "$to" ]; then
        mkdir -p "$to"
    fi

    echo "Linking all in $target to $to"

    for f in "$from"/*; do
        name="$(basename "$f")"
        ln -fns "$f" "$to/${name}"
    done
}

# Link common config
link_all bin "$home/.local/bin"
link fish
link git
link_all gnupg "$home/.gnupg"
link npm
link shell/profile "$home/.profile"
link ranger "$config/ranger"
link tig
link tmux/tmux.conf "$home/.tmux.conf"
link_all vim "$home/.vim"

# Link host specific config
if [ "$(uname)" = Linux ]; then
    link sublime-merge "$config/sublime-merge/Packages/User"
    link sublime-text "$config/sublime-text-3/Packages/User"
    link sublime-text/plugins "$config/sublime-text-3/Packages/UserPlugins"
elif [ "$(uname)" = Darwin ]; then
    link_all launch-agents "$home/Library/LaunchAgents"
    link_all mac/services "$home/Library/Services"
    link sublime-merge "$home/Library/Application Support/Sublime Merge/Packages/User"
    link sublime-text "$home/Library/Application Support/Sublime Text 3/Packages/User"
    link sublime-text/plugins "$home/Library/Application Support/Sublime Text 3/Packages/UserPlugins"
    link xcode/themes "$home/Library/Developer/Xcode/UserData/FontAndColorThemes"
fi
