#!/usr/bin/env bash

set -e

base="${DOTFILES_HOME:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"}"
home="$HOME"
config="${XDG_CONFIG_HOME:-"$home/.config"}"
data="${XDG_DATA_HOME:-"$home/.local/share"}"

link() {
    target="$1"
    from="$base/$target"
    to="${2:-$config/$1}"
    to_parent="$(dirname "$to")"

    if [ ! -d "$to_parent" ]; then
        mkdir -p "$to_parent"
    fi

    echo "Linking $target to $to"

    ln -fns "$from" "$to"
}

link_all() {
    target="$1"
    from="$base/$target"
    to="$2"

    if [ ! -d "$to" ]; then
        mkdir -p "$to"
    fi

    echo "Linking all in $target to $to"

    for f in "$from"/*; do
        name="$(basename "$f")"
        ln -fns "$f" "$to/${name}"
    done
}

link_dir() {
    from="$1"
    to="$2"

    echo "Linking $from to $to"

    ln -fns "$from" "$to"
}

# Link common config
link_all bin "$home/.local/bin"
link alacritty
link fish
link git
link npm
link tig
link shell/profile "$home/.profile"
link tmux/tmux.conf "$home/.tmux.conf"
link zsh/zshrc "$home/.zshrc"
link_all ranger "$config/ranger"
link_all vim "$home/.vim"
link_dir "$home/.vim" "$config/nvim"

# Link host specific config
if [ "$(uname)" = 'Linux' ]; then
    link_all applications "$data/applications"
    link clipit
    link compton/compton.conf "$config/compton.conf"
    link display
    link dunst
    link fontconfig
    link gnupg/gpg-agent.conf "$home/.gnupg/gpg-agent.conf"
    link i3
    link i3status
    link openbox
    link rofi
    link sublime "$config/sublime-text-3/Packages/User"
    link sublime/plugins "$config/sublime-text-3/Packages/UserPlugins"
    link tint2
    link xdg/user-dirs.dirs "$config/user-dirs.dirs"
    link xdg/user-dirs.locale "$config/user-dirs.locale"
    link vscode "$config/vscode/User"
    link x11/Xresources
    link x11/xsessionrc "$home/.xsessionrc"
elif [ "$(uname)" = 'Darwin' ]; then
    link launch-agents/env-sync.plist "$home/Library/LaunchAgents/env-sync.plist"
    link sublime "$home/Library/Application Support/Sublime Text 3/Packages/User"
    link sublime/plugins "$home/Library/Application Support/Sublime Text 3/Packages/UserPlugins"
    link vscode "$home/Library/Application Support/Code/User"
fi
