#!/usr/bin/env bash

set -e

base_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

base="${DOTFILES_HOME:-$base_dir}"
home="$HOME"
config="${XDG_CONFIG_HOME:-$home/.config}"
data="${XDG_DATA_HOME:-$home/.local/share}"

function link() {
    from="$base/$1"
    from_base="$(dirname "$from")"

    to="${2:-$config/$1}"
    to_base="$(dirname "$to")"

    if [ ! -d "$to_base" ]; then
        mkdir -p "$to_base"
    fi

    echo "Linking $from to $to"
    ln -fns "$from" "$to"
}

# Link config
if [ "$(uname)" = 'Linux' ]; then
    link clipit
    link compton/compton.conf $config/compton.conf
    link display
    link dunst
    link fish/aliases.fish $config/fish/aliases.fish
    link fish/config.fish $config/fish/config.fish
    link fish/fishfile $config/fish/fishfile
    link fish/fish_prompt.fish $config/fish/functions/fish_prompt.fish
    link fontconfig
    link git
    link i3
    link i3status
    link npm
    link openbox
    link rofi
    link sublime $config/sublime-text-3/Packages/User
    link sublime/plugins $config/sublime-text-3/Packages/UserPlugins
    link tint2
    link xdg/user-dirs.dirs $config/user-dirs.dirs
    link xdg/user-dirs.locale $config/user-dirs.locale
    link vscode $config/vscode/User
    link x11/Xresources
    link gnupg/gpg-agent.conf $home/.gnupg/gpg-agent.conf
    link shell/profile $home/.profile
    link tmux/tmux.conf $home/.tmux.conf
    link vim/vimrc $home/.vim/vimrc
    link vim/vimrc $home/.vim/init.vim
    link x11/xsessionrc $home/.xsessionrc
elif [ "$(uname)" = 'Darwin' ]; then
    link fish/aliases.fish $config/fish/aliases.fish
    link fish/config.fish $config/fish/config.fish
    link fish/fishfile $config/fish/fishfile
    link fish/fish_prompt.fish $config/fish/functions/fish_prompt.fish
    link git
    link npm
    link shell/profile $home/.profile
    link tmux/tmux.conf $home/.tmux.conf
    link vim/vimrc $home/.vim/vimrc
    link vim/vimrc $home/.vim/init.vim
    link vscode "$home/Library/Application Support/Code/User"
    link sublime "$home/Library/Application Support/Sublime Text 3/Packages/User"
    link sublime/plugins "$home/Library/Application Support/Sublime Text 3/Packages/UserPlugins"
    link launch-agents/env-sync.plist "$home/Library/LaunchAgents/env-sync.plist"
fi

# Post shell configuration
mkdir -p $data/applications $home/bin $home/development $home/scripts
ln -fns $home/.vim $config/nvim
ln -fs $base/scripts/* $home/scripts
ln -fs $base/applications/* $data/applications
$base/scripts/utilities/link-scripts.sh $base/scripts/utilities $home/bin
$base/scripts/utilities/link-scripts.sh $base/scripts/linux $home/bin
