#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

[ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"

# Start specified window manager (default to i3)
session=${1:-i3}

case $session in
    bspwm)
        sxhkd &
        exec bspwm
        ;;
    gnome)
        exec gnome-session
        ;;
    i3|i3wm)
        exec i3
        ;;
    openbox)
        exec openbox-session
        ;;
    xfce|xfce4)
        exec startxfce4
        ;;
    *)
        exec $1
        ;;
esac
