#!/bin/sh

[ -f "$HOME/.profile" ] && . "$HOME/.profile"

# Configure terminal
xset b off
xset m 1 0
xsetroot -cursor_name left_ptr

# Load X resources
[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

# Start the gpg-agent if not already running
export GPG_TTY=$(tty)
if ! pgrep -x -u "$USER" gpg-agent >/dev/null 2>&1; then
    gpg-agent --homedir "$HOME/.gnupg" --enable-ssh-support --daemon > /dev/null 2>&1
    gpg-connect-agent updatestartuptty /bye > /dev/null
fi

# Set SSH to use gpg-agent
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$HOME/.gnupg/S.gpg-agent.ssh"
fi

# Display
[ -x ~/.fehbg ] && sh ~/.fehbg &
if type nvidia-settings > /dev/null 2>&1; then
    nvidia-settings --load-config-only
fi
if type xcalib > /dev/null 2>&1; then
    xcalib "$HOME/.config/display/qnix-120-6500k.profile" &
fi

# Applications
compton -b
dropbox start -i &
clipit &
nm-applet &
