tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"

brew "autojump"
brew "bash"
brew "carthage"
brew "cloc"
brew "cocoapods"
brew "coreutils"
brew "curl"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "git"
brew "gnupg"
brew "haskell-stack"
brew "jq"
brew "mas"
brew "node"
brew "pinentry-mac"
brew "ranger"
brew "rename"
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "swiftformat"
brew "swiftlint"
brew "tig"
brew "tmux"
brew "vim"
brew "wget"

cask "1password"
cask "alfred"
cask "bartender"
cask "dash"
cask "docker"
cask "firefox"
cask "iina"
cask "istat-menus"
cask "launchcontrol"
cask "little-snitch"
cask "marked"
cask "paw"
cask "private-internet-access"
cask "sublime-merge"
cask "sublime-text-dev"
cask "spotify"
cask "transmit"
cask "caskroom/fonts/font-fontawesome"
cask "caskroom/fonts/font-hack"
cask "caskroom/fonts/font-hasklig"
cask "caskroom/fonts/font-source-code-pro"

# mas "Amphetamine", id: 937984704
# mas "Bear", id: 1091189122
# mas "Bible Study", id: 472790630
# mas "Clean Text Menu", id: 1222295315
# mas "Copied", id: 1026349850
# mas "Magnet", id: 441258766
# mas "PCalc", id: 403504866
# mas "Reeder", id: 880001334
# mas "Things3", id: 904280696
# mas "Tweetbot", id: 557168941
# mas "Wipr", id: 1320666476
