#!/usr/bin/env bash
#
# Set login environment variables on macOS

: "${ZDOTDIR:="$HOME/.config/zsh"}"

for zshfile in "$ZDOTDIR/.zshenv" "$ZDOTDIR/.zprofile" "$ZDOTDIR/.zprofile.local"; do
    if [ -f "$zshfile" ]; then
        # Source file to expand necessary environment variables
        . "$zshfile"

        # Read exported variables into the macOS launchctl environment
        grep "^export" "$zshfile" | while IFS=' =' read ignoreexport envvar ignorevalue; do
            launchctl setenv "${envvar}" "${!envvar}"
        done
    fi
done
