" Plugins {{{

if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" Features
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'justinmk/vim-sneak'
Plug 'matze/vim-move'
Plug 'junegunn/vim-peekaboo'
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-gitgutter'
Plug 'terryma/vim-multiple-cursors'
Plug 'christoomey/vim-tmux-navigator'

" Languages
Plug 'octol/vim-cpp-enhanced-highlight', { 'for': 'cpp' }
Plug 'rust-lang/rust.vim', { 'for': 'rust' }
Plug 'keith/swift.vim', { 'for': 'swift' }
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'mxw/vim-jsx', { 'for': 'javascript' }
Plug 'dag/vim-fish', { 'for': 'fish' }
Plug 'junegunn/goyo.vim', { 'for': 'markdown' }

" Visual/themes
Plug 'chriskempson/base16-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

" }}}

" Plugin configuration {{{

" netrw
let g:netrw_liststyle = 3

" GitGutter
let g:gitgutter_eager = 1
let g:gitgutter_realtime = 1
let g:gitgutter_override_sign_column_highlight = 0
set signcolumn=yes

" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme = 'base16'

" }}}

" Options {{{

" UI
set number
set showmatch
set matchtime=2
set whichwrap+=h,l
set updatetime=500

" Searching
set ignorecase
set smartcase

" Tabs
set splitbelow
set splitright

" Always replace tabs with 4 spaces
retab
set expandtab
set shiftwidth=4
set tabstop=4

" Indentation
set smartindent
set wrap

" Ignore certain files and directories
set wildignore+=*.o,*~,*.pyc,*/.git/*,*/node_modules/*
set viminfo=
set noswapfile

" Set language specific options
autocmd Filetype haskell setlocal tabstop=2 shiftwidth=2
autocmd Filetype javascript setlocal tabstop=2 shiftwidth=2
autocmd Filetype ruby setlocal tabstop=2 shiftwidth=2
autocmd Filetype swift setlocal tabstop=2 shiftwidth=2

" }}}

" Colour scheme {{{

set background=dark
let base16colorspace=256
silent! colorscheme base16-oceanicnext
highlight LineNr ctermbg=black
highlight SignColumn ctermbg=black

" }}}

" Keybindings {{{

" Quick leader actions
let maplocalleader = "\\"
let mapleader = "\<space>"

" Disable highlight
nnoremap <silent> <Esc> :nohlsearch<Bar>:echo<cr>
nnoremap <silent> <C-C> :nohlsearch<Bar>:echo<cr>
nnoremap <silent> <C-[> :nohlsearch<Bar>:echo<cr>
nnoremap <silent> <localleader><space> :noh<cr>

" Fast actions
nmap <localleader>w :write<cr>
nmap <localleader>x :exit<cr>
nmap <localleader>q :quit<cr>
nmap <localleader>Q :quitall<cr>
nmap <localleader>f :Files<cr>
nmap <localleader>b :Buffers<cr>
nmap <localleader>c :Commands<cr>
nmap <localleader>r :redraw!<cr>

" Window layer
nnoremap <leader>wj <C-W>j
nnoremap <leader>wk <C-W>k
nnoremap <leader>wh <C-W>h
nnoremap <leader>wl <C-W>l
nnoremap <leader>wJ <C-W>J
nnoremap <leader>wK <C-W>K
nnoremap <leader>wH <C-W>H
nnoremap <leader>wL <C-W>L
nnoremap <leader>ws :split<cr>
nnoremap <leader>wv :vsplit<cr>
nnoremap <leader>wns :new<cr>
nnoremap <leader>wnv :vnew<cr>
nnoremap <leader>wnj :rightbelow :split<cr>
nnoremap <leader>wnk :leftabove :split<cr>
nnoremap <leader>wnh :leftabove :vsplit<cr>
nnoremap <leader>wnl :rightbelow :vsplit<cr>
nnoremap <leader>w= <C-W>=
nnoremap <leader>w- :resize -5<cr>
nnoremap <leader>w+ :resize +5<cr>
nnoremap <leader>wq :quit<cr>

" Tab layer
nnoremap <leader>th :tabprevious<cr>
nnoremap <leader>tl :tabnext<cr>
nnoremap <leader>tH :tabfirst<cr>
nnoremap <leader>tL :tablast<cr>
nnoremap <leader>tn :tabnew<cr>
nnoremap <leader>to :tabonly<cr>
nnoremap <leader>tq :tabclose<cr>
nnoremap <leader>tm :tabmove<cr>

" Buffer layer
nnoremap <leader>bh :bprevious<cr>
nnoremap <leader>bl :bnext<cr>
nnoremap <leader>bH :bfirst<cr>
nnoremap <leader>bL :blast<cr>
nnoremap <leader>bq :bdelete<cr>
nnoremap <leader>bb :Buffers<cr>

" Git layer
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gb :Gblame<cr>
nnoremap <leader>gl :Glog<cr>
nnoremap <leader>gg :Gbrowse<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gf :Gfetch<cr>
nnoremap <leader>gp :Gpull<cr>
nnoremap <leader>gt :terminal tig<cr>
nnoremap <leader>gh :terminal tig %<cr>

" Jump to definition/between headers
nnoremap <F2> gD

" fzf
nnoremap <F9> :Files<cr>
nnoremap <F10> :Buffers<cr>
nnoremap <C-p> :GFiles<cr>

" Sneak
nmap f <Plug>Sneak_f
nmap F <Plug>Sneak_F
xmap f <Plug>Sneak_f
xmap F <Plug>Sneak_F
omap f <Plug>Sneak_f
omap F <Plug>Sneak_F
nmap t <Plug>Sneak_t
nmap T <Plug>Sneak_T
xmap t <Plug>Sneak_t
xmap T <Plug>Sneak_T
omap t <Plug>Sneak_t
omap T <Plug>Sneak_T

" }}}

" vim:foldmethod=marker:foldlevel=0
