" Options {{{

set nocompatible

" netrw
let g:netrw_banner=0
let g:netrw_liststyle=3

" UI
" set number
set nomodeline
set belloff=all

" Searching
set hlsearch
set ignorecase
set smartcase

" Tabs
set splitbelow
set splitright

" Always replace tabs with 2 spaces
set expandtab
set shiftwidth=2
set tabstop=2

" Indentation
set smartindent

" Ignore certain files and directories
set wildignore+=*.o,*~,*.pyc,*/.git/*,*/node_modules/*
set viminfo=
set noswapfile

" }}}

" Keybindings {{{

" fzf
nnoremap <F9> :Files<cr>
nnoremap <F10> :Buffers<cr>

" Window resizing
nnoremap <D-left> :vertical resize -5<cr>
nnoremap <D-down> :resize +5<cr>
nnoremap <D-up> :resize -5<cr>
nnoremap <D-right> :vertical resize +5<cr>

" }}}

" vim:foldmethod=marker:foldlevel=0
