" Options {{{

set nocompatible

" netrw
let g:netrw_banner=0
let g:netrw_liststyle=3

" UI
" set number
set nomodeline
set belloff=all

" Searching
set hlsearch
set ignorecase
set smartcase

" Tabs
set splitbelow
set splitright

" Always replace tabs with 2 spaces
set expandtab
set shiftwidth=2
set tabstop=2

" Indentation
set smartindent

" Ignore certain files and directories
set wildignore+=*.o,*~,*.pyc,*/.git/*,*/node_modules/*
set viminfo=
set noswapfile

" }}}

" Keybindings {{{

" Buffers
nnoremap <Space> :buffers<CR>:buffer<Space>
nnoremap gb :bNext<CR>
nnoremap gB :bprevious<CR>
nnoremap ]b :bNext<CR>
nnoremap [b :bprevious<CR>

" Tabs
nnoremap <C-w>t :tab split<CR>
nnoremap <C-w><C-t> :tab split<CR>
nnoremap ]t :tabNext<CR>
nnoremap [t :tabprevious<CR>

" Errors
nnoremap ]c :cNext<CR>
nnoremap [c :cprevious<CR>
nnoremap ]l :lNext<CR>
nnoremap [l :lprevious<CR>

" fzf
nnoremap <F9> :Files<CR>
nnoremap <F10> :Buffers<CR>

" Window resizing
nnoremap <D-left> :vertical resize -5<CR>
nnoremap <D-down> :resize +5<CR>
nnoremap <D-up> :resize -5<CR>
nnoremap <D-right> :vertical resize +5<CR>

" }}}

" vim:foldmethod=marker:foldlevel=0
