#!/usr/bin/env bash

function confirmation_prompt() {
    message="$1"
    default="${2:-Y}"
    while true; do
        read -p "${message} [Y/n] " input
        case "${input:-$default}" in
            [Yy]|[Yy][Ee][Ss])
                return 0
                ;;
            [Nn]|[Nn][Oo])
                return 1
                ;;
            *)
                echo "Invalid selection"
                ;;
        esac
    done
}

function install_homebrew() {
    if ! type brew > /dev/null 2>&1; then
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    brew update
    brew upgrade
}

function install_homebrew_packages() {
    packages=$1
    for package in ${packages}; do
        brew install $package
    done
}

function install_homebrew_casks() {
    packages=$1
    for package in ${packages}; do
        brew install Caskroom/cask/$package
    done
}

function install_rust() {
    type rustup > /dev/null 2>&1 || curl https://sh.rustup.rs -sSf | sh
    rustup update
    rustup install stable
    rustup install nightly
}

function post_install_configuration() {
    [ "$SHELL" = "/bin/zsh" ] || chsh -s /bin/zsh
    "$HOME/.config/fzf/install" --bin
    vim +PluginInstall +qall
}

function silent() {
    [ "$1" = "-y" ] || [ "$1" = "--yes" ]
}

script_dir="$(dirname "${BASH_SOURCE[0]}")"

[ -f "${HOME}/.profile" ] && source "${HOME}/.profile"

if silent "$1" || confirmation_prompt "Install homebrew?"; then
    install_homebrew
fi
if silent "$1" || confirmation_prompt "Install homebrew packages?"; then
    install_homebrew_packages "$(cat "$script_dir/packages.txt")"
fi
if silent "$1" || confirmation_prompt "Install homebrew casks?"; then
    install_homebrew_casks "$(cat "$script_dir/casks.txt")"
fi
if silent "$1" || confirmation_prompt "Install development tools?"; then
    install_rust
fi
if silent "$1" || confirmation_prompt "Configure environment?"; then
    post_install_configuration
fi

exit 0
