#!/usr/bin/env bash
#
# lemonbar input parser for bspwm

source ~/.config/panel/colours

function window_title() {
    if [[ !  -z  $1  ]] ; then
        echo "%{A:bspc desktop -l next:}%{B$base01}  $1  %{B-}%{A}"
    fi
}

function window_layout() {
    echo "%{A:bspc desktop -l next:}%{B$base01}  $1  %{B-}%{A}"
}

function active_urgent_desktop() {
    echo "%{A:bspc desktop -f $1:}%{F$base08}%{B$base01}%{U$base08}%{+u}  $1  %{-u}%{B-}%{F-}%{A}"
}

function inactive_urgent_desktop() {
    echo "%{A:bspc desktop -f $1:}%{F$base08}%{B$base01}  $1  %{B-}%{F-}%{A}"
}

function active_occupied_desktop() {
    echo "%{A:bspc desktop -f $1:}%{F$base0D}%{B$base01}%{U$base0D}%{+u}  $1  %{-u}%{B-}%{F-}%{A}"
}

function inactive_occupied_desktop() {
    echo "%{A:bspc desktop -f $1:}%{B$base01}  $1  %{B-}%{A}"
}

function active_free_desktop() {
    echo "%{A:bspc desktop -f $1:}%{F$base0D}%{B$base01}%{U$base0D}%{+u}  $1  %{-u}%{B-}%{F-}%{A}"
}

function inactive_free_desktop() {
    echo "%{A:bspc desktop -f $1:}%{B$base01}  $1  %{B-}%{A}"
}

function get_window_info() {
    line=$1
    window_info=""
    IFS=':'
    set -- $line
    while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
            O*) window_info+="$(active_occupied_desktop $name)" ;;
            F*) window_info+="$(active_free_desktop $name)" ;;
            U*) window_info+="$(active_urgent_desktop $name)" ;;
            o*) window_info+="$(inactive_occupied_desktop $name)" ;;
            f*) window_info+="$(inactive_free_desktop $name)" ;;
            u*) window_info+="$(inactive_urgent_desktop $name)" ;;
            L*) window_info+="  |  $(window_layout $name)  " ;;
        esac
        shift
    done

    echo "${window_info}"
}

while read -r line ; do
    case $line in
        S*) system_info="${line#?}" ;;
        T*) title="$(window_title ${line#?})" ;;
        W*) window_info="$(get_window_info ${line#?})" ;;
    esac

    echo "%{l}${window_info}%{c}${title}%{r}${system_info}"
done
