#!/usr/bin/env bash

source ~/.config/panel/colours
source ~/.config/panel/config

if [ $(pgrep -cx panel) -gt 1 ]; then
    echo "The panel is already running." >&2 && exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$panel_fifo" ] && rm "$panel_fifo"
mkfifo "$panel_fifo"

bspc subscribe > "$panel_fifo" &
xtitle -sf 'T%s' > "$panel_fifo" &
~/.config/panel/status > "$panel_fifo" &
~/.config/panel/bar < "$panel_fifo" | \
    lemonbar -p -g "$panel_geometry" -f "$panel_font_1" -f "$panel_font_2" -B "$base01" -F "$base05" | sh &

if [ $commands[stalonetray] ]; then
    stalonetray --background "$base01" --geometry 1x1-280+6 --icon-size 16 &
fi

wait
