#!/bin/sh

source ~/.config/panel/colours

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width 1
bspc config window_gap 25
bspc config split_ratio 0.50

bspc config top_padding 28
bspc config bottom_padding 5
bspc config left_padding 5
bspc config right_padding 5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config auto_alternate false
bspc config auto_cancel true

bspc config normal_border_color "$base01"
bspc config focused_border_color "$base0D"
bspc config presel_border_color "$base0D"
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 1.0

bspc rule -a scratchpad follow=on state=floating
bspc rule -a Plank state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a xmessage state=floating
bspc rule -a dunst state=floating
bspc rule -a file-roller state=floating

bspc rule -a google-chrome desktop='^2'
bspc rule -a Atom desktop='^3'
bspc rule -a Sublime_text desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a Deadbeef desktop='^4'

if [ -s "$HOME/bin/panel" ]; then
    (sleep 1 && "$HOME/bin/panel") &
fi
