set -q XDG_BIN_HOME; or set -gx XDG_BIN_HOME "$HOME/.local/bin"
set -q XDG_DATA_HOME; or set -gx XDG_DATA_HOME "$HOME/.local/share"
set -q XDG_CONFIG_HOME; or set -gx XDG_CONFIG_HOME "$HOME/.config"
set -q XDG_CACHE_HOME; or set -gx XDG_CACHE_HOME "$HOME/.cache"
set -q DOTFILES_HOME; or set -gx DOTFILES_HOME "$HOME/.dotfiles"
