#
# Executes commands at the start of an interactive session.
#

# Source default profile
[ -f "$HOME/.profile" ] && source "$HOME/.profile"
[ -f "$ZDOTDIR/.zim/init.zsh" ] && source "$ZDOTDIR/.zim/init.zsh"
[ -f "$ZDOTDIR/zsh.aliases" ] && source "$ZDOTDIR/zsh.aliases"
[ -f "$ZDOTDIR/zsh.env" ] && source "$ZDOTDIR/zsh.env"
[ -f "$ZDOTDIR/zsh.keys" ] && source "$ZDOTDIR/zsh.keys"
[ -f "$ZDOTDIR/zsh.opts" ] && source "$ZDOTDIR/zsh.opts"
[ -f "$ZDOTDIR/zsh.prompt" ] && source "$ZDOTDIR/zsh.prompt"

# History substring search
if [ -f "$ZDOTDIR/zsh.history-substring-search" ]; then
    source "$ZDOTDIR/zsh.history-substring-search"
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
    bindkey -M vicmd 'k' history-substring-search-up
    bindkey -M vicmd 'j' history-substring-search-down
fi

# Fuzzy command line search
if [ -d "$XDG_CONFIG_HOME/fzf" ]; then
    export FZF_COMPLETION_TRIGGER='~~'
    export PATH="$PATH:$XDG_CONFIG_HOME/fzf/bin"
    export MANPATH="$MANPATH:$XDG_CONFIG_HOME/fzf/man"
    source "$XDG_CONFIG_HOME/fzf/shell/completion.zsh" 2> /dev/null
fi

# Enhancd
if [ -f "$HOME/scripts/enhancd.sh" ]; then
    export ENHANCD_DIR="$XDG_DATA_HOME/enhancd"
    source "$HOME/scripts/enhancd.sh"
fi

# De-duplicate array paths
typeset -gU cdpath fpath mailpath path

if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Temporary Files
if [ ! -d "$TMPDIR" ]; then
    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
