#
# Executes commands at the start of an interactive session.
#

# Export home path
if [ -d "$HOME/bin" ]; then
    export PATH="$HOME/bin:$PATH"
fi

# Load prezto plugins
if [ -s "$ZDOTDIR/.zprezto/init.zsh" ]; then
    source "$ZDOTDIR/.zprezto/init.zsh"
fi

# Load OS specific configuration
if [ -s "$ZDOTDIR/.zshrc.env" ]; then
    source "$ZDOTDIR/.zshrc.env"
fi

# Docker
if [ $commands[docker] ]; then
    alias docker-stop="$HOME/scripts/docker/stop_all_containers.sh"
    alias docker-clean="$HOME/scripts/docker/remove_all_containers.sh"
    alias docker-purge="$HOME/scripts/docker/remove_all_images.sh"
fi

# Clipboard
if [ $commands[xclip] ]; then
    alias setclip='xclip -selection clipboard -i'
    alias getclip='xclip -selection clipboard -o'
fi

# Fuzzy command line search
if [ -s "$ZDOTDIR/.fzf.zsh" ]; then
    source "$ZDOTDIR/.fzf.zsh"
fi

# Enhancd
if [ -s "$HOME/scripts/enhancd.sh" ]; then
    export ENHANCD_DIR="$XDG_DATA_HOME/enhanced"
    source "$HOME/scripts/enhancd.sh"
fi

# Bundle
if [ $commands[bundle] ]; then
    alias be='bundle exec'
    alias ber='bundle exec rake'
fi

# Rust
export CARGO_HOME="${CARGO_HOME:-$HOME/.cargo}"
export PATH="$CARGO_HOME/bin:$PATH"

# Common tool aliases
alias mkdir='mkdir -p'
alias less='less -FSRXc'
alias qfind='find . -name'
alias prettyjson='python -m json.tool'

# Create and navigate to a directory
function mkcd() {
    mkdir -p "$1" && cd "$1"
}
