[ -f "$ZDOTDIR/aliases" ] && source "$ZDOTDIR/aliases"
[ -f "$ZDOTDIR/completions" ] && source "$ZDOTDIR/completions"
[ -f "$ZDOTDIR/colours" ] && source "$ZDOTDIR/colours"
[ -f "$ZDOTDIR/env" ] && source "$ZDOTDIR/env"
[ -f "$ZDOTDIR/keybindings" ] && source "$ZDOTDIR/keybindings"
[ -f "$ZDOTDIR/opts" ] && source "$ZDOTDIR/opts"
[ -f "$ZDOTDIR/prompt" ] && source "$ZDOTDIR/prompt"

# History substring search
if [ -d "$DOTFILES_HOME/libs/zsh-history-substring-search" ]; then
    source "$DOTFILES_HOME/libs/zsh-history-substring-search/zsh-history-substring-search.zsh"
    bindkey '^[[A' history-substring-search-up
    bindkey '^[[B' history-substring-search-down
    bindkey -M vicmd 'k' history-substring-search-up
    bindkey -M vicmd 'j' history-substring-search-down
fi

# Fuzzy command line search
if [ -d "$DOTFILES_HOME/libs/fzf" ]; then
    export PATH="$DOTFILES_HOME/libs/fzf/bin:$PATH"
    export MANPATH="$DOTFILES_HOME/libs/fzf/man:$MANPATH"
    source "$DOTFILES_HOME/libs/fzf/shell/completion.zsh" > /dev/null 2>&1
fi

# Enhancd
if [ -f "$DOTFILES_HOME/libs/enhancd/init.sh" ]; then
    export ENHANCD_DIR="$XDG_DATA_HOME/enhancd"
    source "$DOTFILES_HOME/libs/enhancd/init.sh"
fi

# De-duplicate array paths
typeset -gU cdpath fpath mailpath path

if (( $#commands[(i)lesspipe(|.sh)] )); then
    export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Temporary Files
if [ ! -d "$TMPDIR" ]; then
    export TMPDIR="/tmp/$LOGNAME"
    mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
