#!/bin/sh

# Add key
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

# Add source
echo 'deb https://apt.dockerproject.org/repo debian-stretch main' | sudo tee /etc/apt/sources.list.d/docker.list

# Update and install
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install docker-engine
