PATH="$XDG_BIN_HOME:/opt/homebrew/bin:${PATH:+:"${PATH}"}"

export GHCUP_USE_XDG_DIRS=1
export STACK_ROOT="$XDG_DATA_HOME/stack"
export CABAL_CONFIG="$XDG_CONFIG_HOME/cabal/config"
export CABAL_DIR="$XDG_DATA_HOME/cabal"
PATH="${PATH:+"${PATH}:"}$CABAL_DIR/bin"

export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
PATH="${PATH:+"${PATH}:"}$CARGO_HOME/bin"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"

export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
export BUNDLE_USER_HOME="$XDG_CONFIG_HOME/bundle"
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundle"

export SQLITE_HISTORY="$XDG_STATE_HOME/sqlite_history"

# Source local zprofile
if [ -f "$ZDOTDIR/.zprofile.local" ]; then
    . "$ZDOTDIR/.zprofile.local"
fi
